# dirtyfrag mitigation: https://github.com/V4bel/dirtyfrag#mitigation

# esp4 and esp6 provide support for Encapsulating Security Payload, part of IPSec.
install esp4 /bin/false
install esp4_offload /bin/false
install esp6 /bin/false
install esp6_offload /bin/false

# other ipsec modules
install ah4 /bin/false
install ah6 /bin/false
install ipcomp /bin/false
install ipcomp6 /bin/false
install af_key /bin/false

# RxRPC network protocol: https://www.kernel.org/doc/html/latest/networking/rxrpc.html
install rxrpc /bin/false

# xfrm, another part of IPSec involved in related exploits
install nft_xfrm /bin/false
install xfrm4_tunnel /bin/false
install xfrm6_tunnel /bin/false
install xfrm_algo /bin/false
install xfrm_interface /bin/false
install xfrm_ipcomp /bin/false
install xfrm_iptfs /bin/false
install xfrm_user /bin/false