name: Cleanup old GHCR images

on:
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:

jobs:
  cleanup-old-images:
    name: Cleanup
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Delete old GHCR images
        uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5.0.0
        with: 
          package-name: 'skyblue'
          package-type: 'container'
          min-versions-to-keep: 30